import { MedicalVisit, NextOfKin } from "@/types";

const insuranceProvider =
  "Prudential Assurance Company Singapore (Pte) Limited";

const user = {
  name: "Melissa Tan",
  email: "melissa.tan@email.com",
  phone: "+1 (555) 123-4567",
  address: "123 Main St, City, State 12345",
  dateOfBirth: "1990-06-15",
  bloodType: "O+",
  allergies: ["Penicillin", "Shellfish"],
  emergencyContact: "John Tan (Husband)",
  memberSince: "2020-03-15",
  patientId: "PAT-2024-001",
  insuranceProvider: insuranceProvider,
  primaryDoctor: "Dr. Sarah Johnson",
};

const insurance = [
  {
    provider: "Prudential Assurance Company Singapore (Pte) Limited",
    plan_name: "PruActive Term",
    policy_number: "PruActive-2024-789456",
    status: "Issued on 08 Jan 2023",
    monthly_premium: 107.52,
    financial_details: {
      "Sum Assured": 1500000,
      "Premium Payment Term": "25 years",
      "Policy Term": "40 years",
      Deductible: null,
      Copay: null,
      "Out-of-Pocket Max": null,
    },
    renewal_date: "Fixed term - no renewal required",
    coverage: [
      "Terminal Illness",
      "Total Permanent Disability",
      "Critical Illness",
      "Early Stage Illness",
    ],
  },
  {
    provider: "Prudential Assurance Company Singapore (Pte) Limited",
    plan_name: "PruActive Protect",
    policy_number: "PruActive-2023-123789",
    status: "Issued on 18 Jan 2023",
    monthly_premium: 111.47,
    financial_details: {
      "Sum Assured": 1500000,
      "Premium Payment Term": "25 years",
      "Policy Term": "25 years",
      Deductible: null,
      Copay: null,
      "Out-of-Pocket Max": null,
    },
    renewal_date: "Fixed term - no renewal required",
    coverage: [
      "Terminal Illness",
      "Total Permanent Disability",
      "Early Stage Illness",
      "Death",
    ],
  },
  {
    provider: "Prudential Assurance Company Singapore (Pte) Limited",
    plan_name: "PRUman",
    policy_number: "PRUman-2025-456123",
    status: "Issued on 23 Jan 2023",
    monthly_premium: 79.45,
    financial_details: {
      "Sum Assured": 500000,
      "Premium Payment Term": "25 years",
      "Policy Term": "Up to age 100",
      Deductible: null,
      Copay: null,
      "Out-of-Pocket Max": null,
    },
    renewal_date: "Auto-renews up to age 100",
    coverage: [
      "Terminal Illness",
      "Total Permanent Disability (up to age 65)",
      "Early Stage Illness (Waiver)",
      "Death",
      "Maturity Value",
    ],
  },
  {
    provider: "Prudential Assurance Company Singapore (Pte) Limited",
    plan_name: "PruShield Premier",
    policy_number: "PruShield-2025-123456",
    status: "Issued on 20 Jan 2023",
    monthly_premium: 54.5,
    financial_details: {
      "Annual Deductible": 3500,
      "Co-insurance": "10%",
      "Out-of-Pocket Max": 3000,
      "Policy Term": "Yearly renewable",
    },
    renewal_date: "Annually",
    coverage: [
      "Emergency Room Visits",
      "Specialist Consultations",
      "Prescription Medications",
      "Mental Health Services",
      "Hospital Room & Board",
      "Surgery & Anaesthesia",
      "ICU",
      "Pre/Post Hospitalisation",
      "Day Surgery",
      "Cancer Treatments",
    ],
  },
  {
    provider: "Prudential Assurance Company Singapore (Pte) Limited",
    plan_name: "PRUPersonal Accident – Comprehensive Plan 3",
    policy_number: "PRUPersonal-2025-123456",
    status: "Issued on 23 Jan 2023",
    monthly_premium: 38.0,
    financial_details: {
      "Accidental Death": 300000,
      "Permanent Disablement": 300000,
      "Accidental Medical Expenses": 4000,
      "Fracture Benefit": 4000,
      "Daily Hospital Cash (Accident)": "150/day (up to 365 days)",
      Physiotherapy: "80/visit (up to 800/year)",
      "Ambulance Fees": 250,
      "Mobility Aid / Home Modification": 5000,
    },
    renewal_date: "Annually",
    coverage: [
      "Emergency Room Visits",
      "Specialist Consultations",
      "Prescription Medications",
      "Dental (Accidental)",
      "Vision (Accidental)",
      "Accidental Death",
      "Permanent Disablement",
      "Hospitalisation (due to accident)",
    ],
  },
];

const nextOfKin: NextOfKin[] = [
  {
    id: "1",
    name: "John Tan",
    relationship: "Husband",
    phone: "+65 9123 4568",
    email: "john.tan@email.com",
    address: "123 Orchard Road, #12-34, Singapore 238858",
    isEmergencyContact: true,
    hospitalStatus: "safe",
  },
  {
    id: "2",
    name: "David Tan",
    relationship: "Father",
    phone: "+65 9987 6543",
    email: "david.tan@email.com",
    address: "456 Jurong West Street 41, #08-15, Singapore 640456",
    isEmergencyContact: false,
    hospitalStatus: "safe",
  },
  {
    id: "3",
    name: "Linda Tan",
    relationship: "Mother",
    phone: "+65 9456 7890",
    email: "linda.tan@email.com",
    address: "456 Jurong West Street 41, #08-15, Singapore 640456",
    isEmergencyContact: false,
    hospitalStatus: "hospitalized",
    hospitalInfo: {
      hospital: "Singapore General Hospital",
      admissionDate: "2024-12-15",
      reason: "Chest pain and shortness of breath",
      currentStage: "Recovery",
      estimatedDischarge: "2024-12-20",
      roomNumber: "Room 314, Cardiology Wing",
      emergencyContact: "David Tan (Husband)",
      stages: [
        {
          stage: "Emergency Admission",
          status: "completed",
          timestamp: "Dec 15, 2:30 PM",
          description: "Initial assessment and triage completed",
          location: "Emergency Department",
          doctor: "Dr. Sarah Chen",
        },
        {
          stage: "Diagnostic Testing",
          status: "completed",
          timestamp: "Dec 15, 4:15 PM",
          description: "ECG, blood work, and chest X-ray completed",
          location: "Diagnostic Center",
          doctor: "Dr. Michael Rodriguez",
        },
        {
          stage: "Treatment",
          status: "completed",
          timestamp: "Dec 15, 7:00 PM",
          description: "Medication administered, condition stabilized",
          location: "Cardiology Unit",
          doctor: "Dr. Emily Watson",
        },
        {
          stage: "Recovery",
          status: "current",
          timestamp: "Dec 16, 8:00 AM",
          description:
            "Patient responding well to treatment, monitoring vitals",
          location: "Room 314, Cardiology Wing",
          doctor: "Dr. Emily Watson",
          estimatedDuration: "2-3 days",
        },
        {
          stage: "Discharge Planning",
          status: "upcoming",
          description: "Preparing discharge instructions and follow-up care",
          location: "Cardiology Wing",
          doctor: "Dr. Emily Watson",
          estimatedDuration: "1 day",
        },
      ],
    },
  },
  {
    id: "4",
    name: "Kevin Tan",
    relationship: "Brother",
    phone: "+65 9321 9876",
    email: "kevin.tan@email.com",
    address: "789 Tampines Avenue 4, #15-22, Singapore 520789",
    isEmergencyContact: false,
    hospitalStatus: "safe",
  },
  {
    id: "5",
    name: "Grace Lim",
    relationship: "Close Friend",
    phone: "+65 9654 3210",
    email: "grace.lim@email.com",
    address: "321 Clementi Avenue 2, #06-11, Singapore 120321",
    isEmergencyContact: false,
    hospitalStatus: "safe",
  },
];

const medicalVisits: MedicalVisit[] = [
  {
    id: "1",
    date: "2021-10-03T22:58:00+08:00",
    hospital: "RMG Connect @ Changi CCF",
    doctor: "Dr Tseng Hsien Cho",
    reason: "SARS-CoV-2 serology screen",
    diagnosis: "No detectable antibodies at time of test",
    treatment: "None required. Monitor for symptoms; follow MOH guidance.",
    followUp: "As needed",
    status: "completed",
  },
  {
    id: "2",
    date: "2022-10-29T10:19:00+08:00",
    hospital: "Raffles Skin & Aesthetics Centre",
    doctor: "Raffles Diagnostica Lab",
    reason: "Annual biochemistry panel",
    diagnosis: "All markers within reference ranges",
    treatment: "Maintain healthy lifestyle; repeat in ~12 months",
    followUp: "12 months",
    status: "completed",
  },
  {
    id: "3",
    date: "2023-10-15T09:05:00+08:00",
    hospital: "Raffles Medical Clinic @ Bugis",
    doctor: "Dr Michelle Tan",
    reason: "Seasonal influenza prevention",
    diagnosis: "No contraindications for FluQuadri®",
    treatment: "Influenza vaccine administered; revaccinate next season",
    followUp: "1 year",
    status: "completed",
  },
  {
    id: "4",
    date: "2023-11-20T11:30:00+08:00",
    hospital: "Raffles Diagnostica Lab (North Bridge Rd)",
    doctor: "Lab Review",
    reason: "Routine lipid & liver follow-up",
    diagnosis: "All markers optimal; slight ↑ GGT but still normal",
    treatment: "Continue current regimen; next screen in 12–18 mo",
    followUp: "12–18 months",
    status: "completed",
  },
  {
    id: "5",
    date: "2024-02-10T16:10:00+08:00",
    hospital: "RMG e-Consult (Telemedicine)",
    doctor: "Dr Rajesh Menon",
    reason: "Acute viral URTI (common cold)",
    diagnosis: "Likely rhinovirus; no red-flag symptoms",
    treatment:
      "Symptomatic care: Paracetamol, lozenges, fluids. e-MC for 2 days",
    followUp: "As needed",
    status: "completed",
  },
  {
    id: "6",
    date: "2025-03-01T13:45:00+08:00",
    hospital: "Raffles Executive Medical Centre @ RH",
    doctor: "Dr Angeline Wee",
    reason: "Migraine – medication review & refill",
    diagnosis: "Good response to zolmitriptan; no MOH",
    treatment: "Refill: Zolmitriptan 2.5 mg ×12. Advised trigger diary",
    followUp: "If ≥4 attacks/month",
    status: "completed",
  },
  {
    id: "7",
    date: "2025-04-09T14:20:00+08:00",
    hospital: "Raffles Executive Medical Centre @ RH",
    doctor: "Dr Angeline Wee",
    reason: "Migraine (acute attack)",
    diagnosis: "Stable exam; no concerning neuro signs",
    treatment: "Zolmitriptan 2.5 mg ×6. 1 tab at onset; max 4/day. MC issued",
    followUp: "As needed",
    status: "completed",
  },
];

export { insurance, medicalVisits, nextOfKin, user };
