import { NextOfKin } from "@/types";

const user = {
  name: "Melissa Tan",
  email: "melissa.tan@email.com",
  phone: "+1 (555) 123-4567",
  address: "123 Main St, City, State 12345",
  dateOfBirth: "1990-06-15",
  bloodType: "O+",
  allergies: ["Penicillin", "Shellfish"],
  emergencyContact: "John Tan (Husband)",
  memberSince: "2020-03-15",
  patientId: "PAT-2024-001",
  insuranceProvider: "Prudential",
  primaryDoctor: "Dr. Sarah Johnson",
};

const nextOfKin: NextOfKin[] = [
  {
    id: "1",
    name: "Jane Smith",
    relationship: "Spouse",
    phone: "+1 (555) 123-4568",
    email: "jane.smith@email.com",
    address: "123 Main St, City, State 12345",
    isEmergencyContact: true,
    hospitalStatus: "safe",
  },
  {
    id: "2",
    name: "Robert Smith",
    relationship: "Father",
    phone: "+1 (555) 987-6543",
    email: "robert.smith@email.com",
    address: "456 Oak Ave, City, State 12345",
    isEmergencyContact: false,
    hospitalStatus: "safe",
  },
  {
    id: "3",
    name: "Mary Johnson",
    relationship: "Sister",
    phone: "+1 (555) 456-7890",
    email: "mary.johnson@email.com",
    address: "789 Pine St, City, State 12345",
    isEmergencyContact: true,
    hospitalStatus: "hospitalized",
    hospitalInfo: {
      hospital: "City General Hospital",
      admissionDate: "2024-12-15",
      reason: "Chest pain and shortness of breath",
      currentStage: "Recovery",
      estimatedDischarge: "2024-12-20",
      roomNumber: "Room 314, Cardiology Wing",
      emergencyContact: "John Smith (Brother)",
      stages: [
        {
          stage: "Emergency Admission",
          status: "completed",
          timestamp: "Dec 15, 2:30 PM",
          description: "Initial assessment and triage completed",
          location: "Emergency Department",
          doctor: "Dr. Sarah Chen",
        },
        {
          stage: "Diagnostic Testing",
          status: "completed",
          timestamp: "Dec 15, 4:15 PM",
          description: "ECG, blood work, and chest X-ray completed",
          location: "Diagnostic Center",
          doctor: "Dr. Michael Rodriguez",
        },
        {
          stage: "Treatment",
          status: "completed",
          timestamp: "Dec 15, 7:00 PM",
          description: "Medication administered, condition stabilized",
          location: "Cardiology Unit",
          doctor: "Dr. Emily Watson",
        },
        {
          stage: "Recovery",
          status: "current",
          timestamp: "Dec 16, 8:00 AM",
          description:
            "Patient responding well to treatment, monitoring vitals",
          location: "Room 314, Cardiology Wing",
          doctor: "Dr. Emily Watson",
          estimatedDuration: "2-3 days",
        },
        {
          stage: "Discharge Planning",
          status: "upcoming",
          description: "Preparing discharge instructions and follow-up care",
          location: "Cardiology Wing",
          doctor: "Dr. Emily Watson",
          estimatedDuration: "1 day",
        },
      ],
    },
  },
  {
    id: "4",
    name: "Michael Chen",
    relationship: "Best Friend",
    phone: "+1 (555) 321-9876",
    email: "michael.chen@email.com",
    address: "321 Elm St, City, State 12345",
    isEmergencyContact: false,
    hospitalStatus: "safe",
  },
  {
    id: "5",
    name: "Sarah Williams",
    relationship: "Colleague",
    phone: "+1 (555) 654-3210",
    email: "sarah.williams@email.com",
    address: "654 Maple Ave, City, State 12345",
    isEmergencyContact: true,
    hospitalStatus: "safe",
  },
];

export { nextOfKin, user };
