import { Patient, RegisteredPatient, Status } from './nurseTypes';

export const initialPatients: Patient[] = [
  {
    id: 'P001',
    name: 'Sarah Chen',
    age: 34,
    phone: '65-9123-4567',
    address: '123 Orchard Road, Singapore',
    gender: 'Female',
    complaint: 'Chest pain and shortness of breath',
    vitals: { bp: '140/90', temp: '37.2°C', hr: '95 bpm', spo2: '96%' },
    allergies: ['Penicillin'],
    medications: ['Aspirin (daily)'],
    medicalHistory: ['Asthma'],
    notes: 'Patient appears anxious. Recent travel history noted.',
    sentiment: 'restless',
    priority: 'P2',
    NOK: 'David Chen (Husband) - 65-8765-4321',
    status: Status.nurse_triage,
    prevStatus: Status.registration,
    nextStatus: Status.doctor_consult,
    waitTime: 25,
    room: 'N/A',
    progress: 2,
    nextAction: 'Nurse assessment',
    timeInStage: 15, // in minutes
    arrivalTime: '2:30 PM',
  },
  {
    id: 'P002',
    name: 'Michael Davis',
    age: 58,
    phone: '65-8234-5678',
    address: '45 Commonwealth Ave, Singapore',
    gender: 'Male',
    complaint: 'Persistent cough and fever',
    vitals: { bp: '120/80', temp: '38.5°C', hr: '78 bpm', spo2: '98%' },
    allergies: [],
    medications: ['Lisinopril (daily)'],
    medicalHistory: ['Hypertension'],
    notes: 'Symptoms started 3 days ago. Exhibits mild fatigue.',
    sentiment: 'calm',
    priority: 'P3',
    NOK: 'Linda Davis (Wife) - 65-7654-3210',
    status: Status.waiting_room,
    prevStatus: Status.nurse_triage,
    nextStatus: Status.doctor_consult,
    waitTime: 40,
    room: 'N/A',
    progress: 3,
    nextAction: 'Awaiting doctor to call',
    timeInStage: 30,
    arrivalTime: '1:45 PM',
  },
  {
    id: 'P003',
    name: 'Jessica Lee',
    age: 12,
    phone: '65-9345-6789',
    address: '78 Serangoon Rd, Singapore',
    gender: 'Female',
    complaint: 'Sprained ankle from sports',
    vitals: { bp: '110/70', temp: '36.8°C', hr: '85 bpm', spo2: '99%' },
    allergies: ['Dust'],
    medications: [],
    medicalHistory: [],
    notes: 'Accompanied by mother. Minor swelling observed.',
    sentiment: 'distressed',
    priority: 'P4',
    NOK: 'Emily Lee (Mother) - 65-9876-5432',
    status: Status.arrived,
    prevStatus: Status.arrived,
    nextStatus: Status.registration,
    waitTime: 5,
    room: 'N/A',
    progress: 1,
    nextAction: 'Head to registration kiosk',
    timeInStage: 5,
    arrivalTime: '3:00 PM',
  },
  {
    id: 'P004',
    name: 'David Wilson',
    age: 76,
    phone: '65-9456-7890',
    address: '9 Bishan St 22, Singapore',
    gender: 'Male',
    complaint: 'Severe abdominal pain',
    vitals: { bp: '150/95', temp: '37.5°C', hr: '102 bpm', spo2: '95%' },
    allergies: ['Shellfish'],
    medications: ['Warfarin (daily)'],
    medicalHistory: ['Type 2 Diabetes', 'Heart Disease'],
    notes: 'Pain onset sudden. Requires immediate attention.',
    sentiment: 'good',
    priority: 'P1',
    NOK: 'Sophie Wilson (Daughter) - 65-6789-0123',
    status: Status.bed_assigned,
    prevStatus: Status.awaiting_bed,
    nextStatus: Status.doctor_consult,
    waitTime: 10,
    room: 'Room 3B',
    progress: 4,
    nextAction: 'Doctor examination',
    timeInStage: 5,
    arrivalTime: '2:50 PM',
  },
  {
    id: 'P005',
    name: 'Emily White',
    age: 29,
    phone: '65-9567-8901',
    address: '10 Marine Parade, Singapore',
    gender: 'Female',
    complaint: 'Routine blood work',
    vitals: { bp: '115/75', temp: '37.0°C', hr: '70 bpm', spo2: '99%' },
    allergies: [],
    medications: ['Oral Contraceptives'],
    medicalHistory: [],
    notes: 'Annual check-up. No acute complaints.',
    sentiment: 'tired',
    priority: 'P3',
    NOK: 'Self',
    status: Status.test_in_progress,
    prevStatus: Status.awaiting_tests,
    nextStatus: Status.await_results,
    waitTime: 15,
    room: 'Lab 2',
    progress: 6,
    nextAction: 'Lab technician to finish tests',
    timeInStage: 10,
    arrivalTime: '1:00 PM',
  },
  {
    id: 'P006',
    name: 'Chris Green',
    age: 45,
    phone: '65-9678-9012',
    address: '11 Yishun Ave 9, Singapore',
    gender: 'Male',
    complaint: 'Severe headache and dizziness',
    vitals: { bp: '130/85', temp: '37.1°C', hr: '88 bpm', spo2: '97%' },
    allergies: ['Sulfa drugs'],
    medications: [],
    medicalHistory: ['Migraines'],
    notes: 'Reports vision disturbances. Requested dark room.',
    sentiment: 'angry',
    priority: 'P2',
    NOK: 'Mark Green (Brother) - 65-6543-2109',
    status: Status.waiting_doctor,
    prevStatus: Status.room_assigned,
    nextStatus: Status.doctor_consult,
    waitTime: 60,
    room: 'Room 1A',
    progress: 5,
    nextAction: 'Doctor to enter room',
    timeInStage: 45,
    arrivalTime: '1:30 PM',
  },
  {
    id: 'P007',
    name: 'Olivia Tan',
    age: 28,
    phone: '65-9789-0123',
    address: '20 Jurong East St 13, Singapore',
    gender: 'Female',
    complaint: 'Migraine with aura',
    vitals: { bp: '118/78', temp: '36.9°C', hr: '72 bpm', spo2: '99%' },
    allergies: [],
    medications: ['Sumatriptan (as needed)'],
    medicalHistory: ['Chronic Migraines'],
    notes: 'Aura started 30 mins ago. Needs quiet room.',
    sentiment: 'distressed',
    priority: 'P3',
    NOK: 'Parents',
    status: Status.waiting_doctor,
    prevStatus: Status.waiting_room,
    nextStatus: Status.doctor_consult,
    waitTime: 45,
    room: 'Room 5',
    progress: 4,
    nextAction: 'Doctor consultation',
    timeInStage: 20,
    arrivalTime: '8:00 AM',
  },
  {
    id: 'P008',
    name: 'Ethan Wong',
    age: 62,
    phone: '65-9890-1234',
    address: '35 Woodlands Ave 2, Singapore',
    gender: 'Male',
    complaint: 'Dizziness and weakness',
    vitals: { bp: '100/60', temp: '37.0°C', hr: '55 bpm', spo2: '97%' },
    allergies: ['Codeine'],
    medications: ['Amlodipine'],
    medicalHistory: ['Hypertension', 'Arrhythmia'],
    notes: 'Felt lightheaded on standing. No chest pain reported.',
    sentiment: 'tired',
    priority: 'P2',
    NOK: 'Wife, Susan Wong - 65-9901-2345',
    status: Status.bed_assigned,
    prevStatus: Status.awaiting_bed,
    nextStatus: Status.doctor_consult,
    waitTime: 10,
    room: 'Bed 12',
    progress: 5,
    nextAction: 'ECG and doctor assessment',
    timeInStage: 5,
    arrivalTime: '8:45 AM',
  },
  {
    id: 'P009',
    name: 'Mia Lim',
    age: 5,
    phone: '65-9012-3456',
    address: '4 Bishan St 13, Singapore',
    gender: 'Female',
    complaint: 'High fever and sore throat',
    vitals: { bp: '90/60', temp: '39.5°C', hr: '110 bpm', spo2: '98%' },
    allergies: [],
    medications: [],
    medicalHistory: ['Recurrent Tonsillitis'],
    notes: 'Child appears lethargic. Accompanied by father.',
    sentiment: 'distressed',
    priority: 'P2',
    NOK: 'Father, Ken Lim - 65-9012-3456',
    status: Status.nurse_triage,
    prevStatus: Status.registration,
    nextStatus: Status.doctor_consult,
    waitTime: 15,
    room: 'N/A',
    progress: 2,
    nextAction: 'Pediatric nurse assessment',
    timeInStage: 10,
    arrivalTime: '9:15 AM',
  },
  {
    id: 'P010',
    name: 'Noah Ganesan',
    age: 40,
    phone: '65-9123-4560',
    address: '50 Bukit Timah Rd, Singapore',
    gender: 'Male',
    complaint: 'Wrist pain after fall',
    vitals: { bp: '125/80', temp: '37.0°C', hr: '75 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Fell playing basketball. Swelling observed.',
    sentiment: 'calm',
    priority: 'P3',
    NOK: 'Wife',
    status: Status.awaiting_tests,
    prevStatus: Status.doctor_consult,
    nextStatus: Status.await_results,
    waitTime: 30,
    room: 'N/A',
    progress: 6,
    nextAction: 'X-ray of wrist',
    timeInStage: 10,
    arrivalTime: '9:00 AM',
  },
  {
    id: 'P011',
    name: 'Chloe Tan',
    age: 72,
    phone: '65-9234-5671',
    address: '6 Toa Payoh Lor 7, Singapore',
    gender: 'Female',
    complaint: 'Difficulty breathing',
    vitals: { bp: '160/90', temp: '37.1°C', hr: '105 bpm', spo2: '90%' },
    allergies: ['NSAIDs'],
    medications: ['Furosemide', 'Digoxin'],
    medicalHistory: ['COPD', 'Heart Failure'],
    notes: 'Wheezing sounds. Oxygen saturation low.',
    sentiment: 'distressed',
    priority: 'P1',
    NOK: 'Daughter, Rachel Tan - 65-9345-6782',
    status: Status.bed_assigned,
    prevStatus: Status.awaiting_bed,
    nextStatus: Status.doctor_consult,
    waitTime: 5,
    room: 'Resuscitation 1',
    progress: 4,
    nextAction: 'Immediate doctor assessment, oxygen therapy',
    timeInStage: 2,
    arrivalTime: '9:50 AM',
  },
  {
    id: 'P012',
    name: 'Liam Koh',
    age: 18,
    phone: '65-9345-6782',
    address: '7 Punggol Central, Singapore',
    gender: 'Male',
    complaint: 'Minor cut on arm',
    vitals: { bp: '115/70', temp: '36.7°C', hr: '68 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Cut from kitchen knife. Superficial, needs cleaning and dressing.',
    sentiment: 'good',
    priority: 'P4',
    NOK: 'Self',
    status: Status.registration,
    prevStatus: Status.arrived,
    nextStatus: Status.waiting_triage,
    waitTime: 10,
    room: 'N/A',
    progress: 1,
    nextAction: 'Complete registration',
    timeInStage: 5,
    arrivalTime: '10:00 AM',
  },
  {
    id: 'P013',
    name: 'Isabella Cheong',
    age: 39,
    phone: '65-9456-7893',
    address: '8 Pasir Ris Dr 6, Singapore',
    gender: 'Female',
    complaint: 'Allergic reaction',
    vitals: { bp: '130/85', temp: '37.0°C', hr: '90 bpm', spo2: '97%' },
    allergies: ['Peanuts'],
    medications: ['EpiPen (carried)'],
    medicalHistory: ['Severe Allergies'],
    notes: 'Exposure to peanuts. Rash and mild swelling.',
    sentiment: 'angry',
    priority: 'P2',
    NOK: 'Husband',
    status: Status.doctor_consult,
    prevStatus: Status.nurse_triage,
    nextStatus: Status.discharge_procedures,
    waitTime: 5,
    room: 'Room 8',
    progress: 5,
    nextAction: 'Doctor to prescribe antihistamines',
    timeInStage: 2,
    arrivalTime: '10:10 AM',
  },
  {
    id: 'P014',
    name: 'James Teo',
    age: 50,
    phone: '65-9567-8904',
    address: '9 Ang Mo Kio Ave 1, Singapore',
    gender: 'Male',
    complaint: 'Follow-up for previous injury',
    vitals: { bp: '128/82', temp: '36.8°C', hr: '70 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: ['Fractured leg (2 weeks ago)'],
    notes: 'Scheduled appointment for cast check.',
    sentiment: 'calm',
    priority: 'P4',
    NOK: 'Self',
    status: Status.await_results,
    prevStatus: Status.test_in_progress,
    nextStatus: Status.doctor_consult,
    waitTime: 10,
    room: 'N/A',
    progress: 7,
    nextAction: 'Review X-ray results with doctor',
    timeInStage: 5,
    arrivalTime: '10:30 AM',
  },
  {
    id: 'P015',
    name: 'Sophia Neo',
    age: 68,
    phone: '65-9678-9015',
    address: '10 Bedok North St 2, Singapore',
    gender: 'Female',
    complaint: 'Chronic back pain flare-up',
    vitals: { bp: '135/88', temp: '37.0°C', hr: '80 bpm', spo2: '97%' },
    allergies: [],
    medications: ['Painkillers (as needed)'],
    medicalHistory: ['Osteoarthritis'],
    notes: 'Pain level 7/10. Limited mobility.',
    sentiment: 'tired',
    priority: 'P3',
    NOK: 'Son, Marcus Neo - 65-9789-0126',
    status: Status.waiting_room,
    prevStatus: Status.nurse_triage,
    nextStatus: Status.doctor_consult,
    waitTime: 50,
    room: 'N/A',
    progress: 3,
    nextAction: 'Awaiting doctor consultation',
    timeInStage: 40,
    arrivalTime: '9:30 AM',
  },
  {
    id: 'P016',
    name: 'Ben Choong',
    age: 22,
    phone: '65-9789-0126',
    address: '11 Clementi Ave 3, Singapore',
    gender: 'Male',
    complaint: 'Sore throat and body aches',
    vitals: { bp: '120/75', temp: '38.0°C', hr: '78 bpm', spo2: '98%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Symptoms started yesterday. No difficulty swallowing.',
    sentiment: 'good',
    priority: 'P4',
    NOK: 'Self',
    status: Status.waiting_triage,
    prevStatus: Status.registration,
    nextStatus: Status.nurse_triage,
    waitTime: 20,
    room: 'N/A',
    progress: 2,
    nextAction: 'Nurse to call for triage',
    timeInStage: 15,
    arrivalTime: '10:45 AM',
  },
  {
    id: 'P017',
    name: 'Grace Tan',
    age: 48,
    phone: '65-9890-1237',
    address: '12 Farrer Park Rd, Singapore',
    gender: 'Female',
    complaint: 'Stomach flu symptoms',
    vitals: { bp: '110/70', temp: '37.8°C', hr: '85 bpm', spo2: '97%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Vomiting and diarrhea. Dehydrated.',
    sentiment: 'tired',
    priority: 'P3',
    NOK: 'Husband',
    status: Status.doctor_consult,
    prevStatus: Status.nurse_triage,
    nextStatus: Status.discharge_procedures,
    waitTime: 10,
    room: 'Room 10',
    progress: 5,
    nextAction: 'Doctor to prescribe anti-emetics',
    timeInStage: 5,
    arrivalTime: '11:00 AM',
  },
  {
    id: 'P018',
    name: 'Daniel Lim',
    age: 7,
    phone: '65-9012-3458',
    address: '13 Hougang Ave 8, Singapore',
    gender: 'Male',
    complaint: 'Ear infection',
    vitals: { bp: '95/65', temp: '38.9°C', hr: '100 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: ['Recurrent Ear Infections'],
    notes: 'Tugging at ear. Fever overnight.',
    sentiment: 'distressed',
    priority: 'P3',
    NOK: 'Mother',
    status: Status.waiting_doctor,
    prevStatus: Status.waiting_room,
    nextStatus: Status.doctor_consult,
    waitTime: 30,
    room: 'N/A',
    progress: 4,
    nextAction: 'Doctor examination',
    timeInStage: 15,
    arrivalTime: '11:20 AM',
  },
  {
    id: 'P019',
    name: 'Megan Sng',
    age: 25,
    phone: '65-9123-4569',
    address: '14 Kallang Bahru, Singapore',
    gender: 'Female',
    complaint: 'Prescription refill',
    vitals: { bp: '110/70', temp: '36.6°C', hr: '65 bpm', spo2: '99%' },
    allergies: [],
    medications: ['Oral Contraceptives'],
    medicalHistory: [],
    notes: 'Routine visit. No new complaints.',
    sentiment: 'good',
    priority: 'P4',
    NOK: 'Self',
    status: Status.complete,
    prevStatus: Status.doctor_consult,
    nextStatus: Status.complete,
    waitTime: 0,
    room: 'N/A',
    progress: 8,
    nextAction: 'Discharge',
    timeInStage: 5,
    arrivalTime: '11:30 AM',
  },
  {
    id: 'P020',
    name: 'Alex Cheng',
    age: 55,
    phone: '65-9234-5670',
    address: '15 Lentor Ave, Singapore',
    gender: 'Male',
    complaint: 'Follow-up on blood test results',
    vitals: { bp: '138/85', temp: '37.0°C', hr: '72 bpm', spo2: '98%' },
    allergies: [],
    medications: [],
    medicalHistory: ['High Cholesterol'],
    notes: 'Patient called earlier about results.',
    sentiment: 'calm',
    priority: 'P3',
    NOK: 'Wife',
    status: Status.await_results,
    prevStatus: Status.test_in_progress,
    nextStatus: Status.doctor_consult,
    waitTime: 20,
    room: 'N/A',
    progress: 7,
    nextAction: 'Doctor to discuss results',
    timeInStage: 10,
    arrivalTime: '10:50 AM',
  },
  {
    id: 'P021',
    name: 'Lynn Phua',
    age: 31,
    phone: '65-9345-6781',
    address: '16 MacPherson Rd, Singapore',
    gender: 'Female',
    complaint: 'Urinary tract infection symptoms',
    vitals: { bp: '120/78', temp: '37.4°C', hr: '80 bpm', spo2: '98%' },
    allergies: [],
    medications: [],
    medicalHistory: ['Recurrent UTIs'],
    notes: 'Dysuria and frequency.',
    sentiment: 'tired',
    priority: 'P3',
    NOK: 'Husband',
    status: Status.nurse_triage,
    prevStatus: Status.registration,
    nextStatus: Status.doctor_consult,
    waitTime: 18,
    room: 'N/A',
    progress: 2,
    nextAction: 'Urinalysis',
    timeInStage: 12,
    arrivalTime: '12:00 PM',
  },
  {
    id: 'P022',
    name: 'Marcus Goh',
    age: 49,
    phone: '65-9456-7892',
    address: '17 Neil Rd, Singapore',
    gender: 'Male',
    complaint: 'Persistent fever post-surgery',
    vitals: { bp: '130/80', temp: '38.8°C', hr: '92 bpm', spo2: '96%' },
    allergies: ['Latex'],
    medications: ['Painkillers'],
    medicalHistory: ['Appendectomy (1 week ago)'],
    notes: 'Concern for post-op infection.',
    sentiment: 'angry',
    priority: 'P2',
    NOK: 'Wife',
    status: Status.awaiting_bed,
    prevStatus: Status.waiting_triage,
    nextStatus: Status.bed_assigned,
    waitTime: 30,
    room: 'N/A',
    progress: 3,
    nextAction: 'Bed allocation for observation',
    timeInStage: 20,
    arrivalTime: '11:10 AM',
  },
  {
    id: 'P023',
    name: 'Chloe Wee',
    age: 6,
    phone: '65-9567-8903',
    address: '18 Outram Park, Singapore',
    gender: 'Female',
    complaint: 'Rash and itching',
    vitals: { bp: '98/62', temp: '37.0°C', hr: '90 bpm', spo2: '99%' },
    allergies: ['Dairy (mild)'],
    medications: [],
    medicalHistory: ['Eczema'],
    notes: 'Generalized rash. Scratching observed.',
    sentiment: 'distressed',
    priority: 'P3',
    NOK: 'Father',
    status: Status.registration,
    prevStatus: Status.arrived,
    nextStatus: Status.waiting_triage,
    waitTime: 10,
    room: 'N/A',
    progress: 1,
    nextAction: 'Complete registration for child',
    timeInStage: 5,
    arrivalTime: '1:00 PM',
  },
  {
    id: 'P024',
    name: 'Ryan Foo',
    age: 19,
    phone: '65-9678-9014',
    address: '19 Pasir Panjang Rd, Singapore',
    gender: 'Male',
    complaint: 'Sports injury - knee pain',
    vitals: { bp: '125/78', temp: '36.9°C', hr: '75 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Twisted knee during soccer. Unable to bear weight.',
    sentiment: 'restless',
    priority: 'P2',
    NOK: 'Parents',
    status: Status.awaiting_bed,
    prevStatus: Status.nurse_triage,
    nextStatus: Status.bed_assigned,
    waitTime: 20,
    room: 'N/A',
    progress: 3,
    nextAction: 'Bed for leg elevation',
    timeInStage: 15,
    arrivalTime: '12:45 PM',
  },
  {
    id: 'P025',
    name: 'Seraphina Quek',
    age: 88,
    phone: '65-9789-0125',
    address: '20 Queen St, Singapore',
    gender: 'Female',
    complaint: 'Fall at home',
    vitals: { bp: '155/90', temp: '36.7°C', hr: '60 bpm', spo2: '95%' },
    allergies: ['Iodine'],
    medications: ['Blood Thinners'],
    medicalHistory: ['Osteoporosis', 'Dementia'],
    notes: 'Witnessed fall. Possible hip fracture. Confused.',
    sentiment: 'tired',
    priority: 'P1',
    NOK: 'Son, Peter Quek - 65-9890-1236',
    status: Status.bed_assigned,
    prevStatus: Status.awaiting_bed,
    nextStatus: Status.doctor_consult,
    waitTime: 5,
    room: 'Emergency Bay 3',
    progress: 4,
    nextAction: 'Immediate doctor assessment, imaging',
    timeInStage: 3,
    arrivalTime: '1:10 PM',
  },
  {
    id: 'P026',
    name: 'Kevin Ho',
    age: 3,
    phone: '65-9890-1236',
    address: '21 River Valley Rd, Singapore',
    gender: 'Male',
    complaint: 'Stomach ache and vomiting',
    vitals: { bp: '85/55', temp: '38.0°C', hr: '120 bpm', spo2: '97%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Child crying, dehydrated. Had suspicious food last night.',
    sentiment: 'distressed',
    priority: 'P2',
    NOK: 'Mother',
    status: Status.nurse_triage,
    prevStatus: Status.arrived,
    nextStatus: Status.doctor_consult,
    waitTime: 10,
    room: 'N/A',
    progress: 2,
    nextAction: 'Pediatric nurse assessment, rehydration',
    timeInStage: 7,
    arrivalTime: '1:30 PM',
  },
  {
    id: 'P027',
    name: 'Joyce Ang',
    age: 42,
    phone: '65-9012-3457',
    address: '22 Sembawang Rd, Singapore',
    gender: 'Female',
    complaint: 'Skin infection on leg',
    vitals: { bp: '122/78', temp: '37.5°C', hr: '78 bpm', spo2: '98%' },
    allergies: ['Tetracycline'],
    medications: [],
    medicalHistory: ['Diabetes (controlled)'],
    notes: 'Redness, swelling, and warmth. Developing rapidly.',
    sentiment: 'calm',
    priority: 'P3',
    NOK: 'Husband',
    status: Status.waiting_doctor,
    prevStatus: Status.waiting_room,
    nextStatus: Status.doctor_consult,
    waitTime: 35,
    room: 'Room 7',
    progress: 4,
    nextAction: 'Doctor examination, wound care plan',
    timeInStage: 20,
    arrivalTime: '1:00 PM',
  },
  {
    id: 'P028',
    name: 'Wei Xuan',
    age: 29,
    phone: '65-9123-4568',
    address: '23 Tampines Ave 5, Singapore',
    gender: 'Male',
    complaint: 'Routine vaccination',
    vitals: { bp: '110/70', temp: '36.8°C', hr: '65 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Scheduled appointment for flu shot.',
    sentiment: 'good',
    priority: 'P4',
    NOK: 'Self',
    status: Status.doctor_consult,
    prevStatus: Status.registration,
    nextStatus: Status.complete,
    waitTime: 10,
    room: 'Room 2',
    progress: 5,
    nextAction: 'Administer vaccine',
    timeInStage: 5,
    arrivalTime: '2:00 PM',
  },
  {
    id: 'P029',
    name: 'Zara Soh',
    age: 16,
    phone: '65-9234-5679',
    address: '24 Upper Thomson Rd, Singapore',
    gender: 'Female',
    complaint: 'Anxiety attack',
    vitals: { bp: '130/80', temp: '37.0°C', hr: '110 bpm', spo2: '98%' },
    allergies: [],
    medications: [],
    medicalHistory: ['GAD'],
    notes: 'Hyperventilating. Appears distressed.',
    sentiment: 'distressed',
    priority: 'P2',
    NOK: 'Mother',
    status: Status.awaiting_bed,
    prevStatus: Status.nurse_triage,
    nextStatus: Status.bed_assigned,
    waitTime: 15,
    room: 'N/A',
    progress: 3,
    nextAction: 'Quiet space for de-escalation',
    timeInStage: 10,
    arrivalTime: '2:15 PM',
  },
  {
    id: 'P030',
    name: 'Sean Tan',
    age: 70,
    phone: '65-9345-6780',
    address: '25 VivoCity, Singapore',
    gender: 'Male',
    complaint: 'Chest discomfort, non-cardiac',
    vitals: { bp: '128/80', temp: '36.8°C', hr: '70 bpm', spo2: '99%' },
    allergies: [],
    medications: ['Antacids'],
    medicalHistory: ['GERD'],
    notes: 'Reports burning sensation after meals. Rules out cardiac.',
    sentiment: 'calm',
    priority: 'P3',
    NOK: 'Wife',
    status: Status.doctor_consult,
    prevStatus: Status.nurse_triage,
    nextStatus: Status.discharge_procedures,
    waitTime: 5,
    room: 'Room 9',
    progress: 5,
    nextAction: 'Doctor to advise on lifestyle changes',
    timeInStage: 3,
    arrivalTime: '2:40 PM',
  },
  {
    id: 'P031',
    name: 'Kelly Peh',
    age: 52,
    phone: '65-9456-7891',
    address: '26 West Coast Plaza, Singapore',
    gender: 'Female',
    complaint: 'Routine health screening',
    vitals: { bp: '120/75', temp: '37.0°C', hr: '75 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Scheduled for comprehensive check-up.',
    sentiment: 'good',
    priority: 'P4',
    NOK: 'Self',
    status: Status.awaiting_tests,
    prevStatus: Status.doctor_consult,
    nextStatus: Status.test_in_progress,
    waitTime: 20,
    room: 'N/A',
    progress: 6,
    nextAction: 'Proceed to blood test lab',
    timeInStage: 10,
    arrivalTime: '2:30 PM',
  },
  {
    id: 'P032',
    name: 'Jason Lim',
    age: 4,
    phone: '65-9567-8902',
    address: '27 Yishun Ring Rd, Singapore',
    gender: 'Male',
    complaint: 'Minor burn on hand',
    vitals: { bp: '90/60', temp: '37.0°C', hr: '100 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Touched hot stove. Small superficial burn.',
    sentiment: 'distressed',
    priority: 'P3',
    NOK: 'Mother',
    status: Status.nurse_triage,
    prevStatus: Status.arrived,
    nextStatus: Status.doctor_consult,
    waitTime: 8,
    room: 'N/A',
    progress: 2,
    nextAction: 'Nurse to dress burn',
    timeInStage: 5,
    arrivalTime: '3:00 PM',
  },
  {
    id: 'P033',
    name: 'Felicia Low',
    age: 65,
    phone: '65-9678-9013',
    address: '28 Zion Rd, Singapore',
    gender: 'Female',
    complaint: 'Follow-up for post-stroke rehabilitation',
    vitals: { bp: '145/88', temp: '36.7°C', hr: '70 bpm', spo2: '98%' },
    allergies: [],
    medications: ['Aspirin', 'Statins'],
    medicalHistory: ['Stroke (6 months ago)'],
    notes: 'Assess motor skills and speech progression.',
    sentiment: 'calm',
    priority: 'P4',
    NOK: 'Son',
    status: Status.waiting_doctor,
    prevStatus: Status.waiting_room,
    nextStatus: Status.doctor_consult,
    waitTime: 50,
    room: 'Rehab Room 1',
    progress: 4,
    nextAction: 'Occupational therapy assessment',
    timeInStage: 25,
    arrivalTime: '2:00 PM',
  },
  {
    id: 'P034',
    name: 'Gary Tham',
    age: 38,
    phone: '65-9789-0124',
    address: '29 East Coast Rd, Singapore',
    gender: 'Male',
    complaint: 'Persistent fever, unknown origin',
    vitals: { bp: '120/75', temp: '39.0°C', hr: '90 bpm', spo2: '96%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Fever for 4 days. No other clear symptoms.',
    sentiment: 'tired',
    priority: 'P2',
    NOK: 'Wife',
    status: Status.awaiting_tests,
    prevStatus: Status.doctor_consult,
    nextStatus: Status.test_in_progress,
    waitTime: 20,
    room: 'N/A',
    progress: 6,
    nextAction: 'Blood tests for infection markers',
    timeInStage: 10,
    arrivalTime: '3:00 PM',
  },
  {
    id: 'P035',
    name: 'Ashley Wong',
    age: 26,
    phone: '65-9890-1235',
    address: '30 Balestier Rd, Singapore',
    gender: 'Female',
    complaint: 'Minor eye irritation',
    vitals: { bp: '110/68', temp: '36.7°C', hr: '68 bpm', spo2: '99%' },
    allergies: ['Pollen'],
    medications: ['Eye drops (as needed)'],
    medicalHistory: [],
    notes: 'Redness and itchiness in left eye.',
    sentiment: 'calm',
    priority: 'P4',
    NOK: 'Self',
    status: Status.waiting_triage,
    prevStatus: Status.registration,
    nextStatus: Status.nurse_triage,
    waitTime: 15,
    room: 'N/A',
    progress: 2,
    nextAction: 'Nurse to assess eye',
    timeInStage: 10,
    arrivalTime: '3:15 PM',
  },
  {
    id: 'P036',
    name: 'Peter Lee',
    age: 60,
    phone: '65-9012-3459',
    address: '31 Commonwealth Cres, Singapore',
    gender: 'Male',
    complaint: 'Leg swelling',
    vitals: { bp: '140/90', temp: '36.8°C', hr: '75 bpm', spo2: '97%' },
    allergies: [],
    medications: ['Diuretics'],
    medicalHistory: ['Congestive Heart Failure'],
    notes: 'Bilateral pitting edema. Worsening over 2 days.',
    sentiment: 'tired',
    priority: 'P2',
    NOK: 'Daughter',
    status: Status.bed_assigned,
    prevStatus: Status.awaiting_bed,
    nextStatus: Status.doctor_consult,
    waitTime: 10,
    room: 'Medical Ward 1',
    progress: 4,
    nextAction: 'Doctor assessment, potential fluid management',
    timeInStage: 5,
    arrivalTime: '3:30 PM',
  },
  {
    id: 'P037',
    name: 'Hazel Tan',
    age: 10,
    phone: '65-9123-4560',
    address: '32 Dover Rd, Singapore',
    gender: 'Female',
    complaint: 'Minor concussion from fall',
    vitals: { bp: '100/65', temp: '36.9°C', hr: '80 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Hit head on playground. Brief loss of consciousness. Vomited once.',
    sentiment: 'distressed',
    priority: 'P2',
    NOK: 'Mother',
    status: Status.nurse_triage,
    prevStatus: Status.arrived,
    nextStatus: Status.doctor_consult,
    waitTime: 10,
    room: 'N/A',
    progress: 2,
    nextAction: 'Neuro assessment by nurse',
    timeInStage: 8,
    arrivalTime: '3:45 PM',
  },
  {
    id: 'P038',
    name: 'Paul Chan',
    age: 78,
    phone: '65-9234-5671',
    address: '33 Fajar Rd, Singapore',
    gender: 'Male',
    complaint: 'Routine wound dressing change',
    vitals: { bp: '130/80', temp: '37.0°C', hr: '70 bpm', spo2: '98%' },
    allergies: [],
    medications: ['Antibiotics'],
    medicalHistory: ['Diabetic Foot Ulcer'],
    notes: 'Post-op check. Wound appears clean.',
    sentiment: 'good',
    priority: 'P4',
    NOK: 'Daughter',
    status: Status.doctor_consult,
    prevStatus: Status.nurse_triage,
    nextStatus: Status.discharge_procedures,
    waitTime: 5,
    room: 'Treatment Room 1',
    progress: 5,
    nextAction: 'Wound redressing by doctor/nurse',
    timeInStage: 3,
    arrivalTime: '4:00 PM',
  },
  {
    id: 'P039',
    name: 'Jamie Soh',
    age: 33,
    phone: '65-9345-6782',
    address: '34 Geylang Rd, Singapore',
    gender: 'Female',
    complaint: 'Sudden onset back spasm',
    vitals: { bp: '128/82', temp: '36.9°C', hr: '75 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Pain in lower back, sharp. Limited movement.',
    sentiment: 'angry',
    priority: 'P3',
    NOK: 'Husband',
    status: Status.waiting_doctor,
    prevStatus: Status.waiting_room,
    nextStatus: Status.doctor_consult,
    waitTime: 40,
    room: 'N/A',
    progress: 4,
    nextAction: 'Doctor to examine back',
    timeInStage: 20,
    arrivalTime: '3:20 PM',
  },
  {
    id: 'P040',
    name: 'Marcus Wee',
    age: 59,
    phone: '65-9456-7893',
    address: '35 Hougang Ave 2, Singapore',
    gender: 'Male',
    complaint: 'Possible urinary retention',
    vitals: { bp: '140/85', temp: '37.0°C', hr: '80 bpm', spo2: '97%' },
    allergies: [],
    medications: ['Tamsulosin'],
    medicalHistory: ['BPH'],
    notes: 'Difficulty passing urine for 12 hours. Bladder distended.',
    sentiment: 'distressed',
    priority: 'P2',
    NOK: 'Wife',
    status: Status.bed_assigned,
    prevStatus: Status.awaiting_bed,
    nextStatus: Status.doctor_consult,
    waitTime: 8,
    room: 'Bed 10',
    progress: 4,
    nextAction: 'Doctor assessment, catheterization',
    timeInStage: 4,
    arrivalTime: '4:10 PM',
  },
  {
    id: 'P041',
    name: 'Nurul Isa',
    age: 2,
    phone: '65-9567-8904',
    address: '36 Jalan Besar, Singapore',
    gender: 'Female',
    complaint: 'Febrile convulsions',
    vitals: { bp: '80/50', temp: '40.1°C', hr: '130 bpm', spo2: '95%' },
    allergies: [],
    medications: [],
    medicalHistory: ['Previous Febrile Seizures'],
    notes: 'Parents witnessed seizure activity. Recovering now.',
    sentiment: 'distressed',
    priority: 'P1',
    NOK: 'Parents',
    status: Status.bed_assigned,
    prevStatus: Status.arrived,
    nextStatus: Status.doctor_consult,
    waitTime: 2,
    room: 'Pediatric Resuscitation',
    progress: 4,
    nextAction: 'Immediate doctor review, antipyretics',
    timeInStage: 1,
    arrivalTime: '4:20 PM',
  },
  {
    id: 'P042',
    name: 'Samuel Ong',
    age: 20,
    phone: '65-9678-9015',
    address: '37 Keong Saik Rd, Singapore',
    gender: 'Male',
    complaint: 'Drunk and disorderly',
    vitals: { bp: '120/70', temp: '36.5°C', hr: '90 bpm', spo2: '98%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Strong alcohol odor. Uncooperative. Accompanied by police.',
    sentiment: 'angry',
    priority: 'P3',
    NOK: 'Parents',
    status: Status.waiting_room,
    prevStatus: Status.registration,
    nextStatus: Status.doctor_consult,
    waitTime: 30,
    room: 'N/A',
    progress: 2,
    nextAction: 'Observation until sober',
    timeInStage: 15,
    arrivalTime: '4:00 PM',
  },
  {
    id: 'P043',
    name: 'Rachel Seow',
    age: 75,
    phone: '65-9789-0120',
    address: '38 Lentor Loop, Singapore',
    gender: 'Female',
    complaint: 'Follow-up for cataract surgery',
    vitals: { bp: '135/85', temp: '36.8°C', hr: '70 bpm', spo2: '98%' },
    allergies: [],
    medications: ['Eye drops'],
    medicalHistory: ['Cataracts'],
    notes: 'Scheduled post-op check. Vision improving.',
    sentiment: 'good',
    priority: 'P4',
    NOK: 'Self',
    status: Status.doctor_consult,
    prevStatus: Status.nurse_triage,
    nextStatus: Status.discharge_procedures,
    waitTime: 5,
    room: 'Eye Clinic',
    progress: 5,
    nextAction: 'Doctor to check eyes',
    timeInStage: 2,
    arrivalTime: '4:30 PM',
  },
  {
    id: 'P044',
    name: 'Bryan Wong',
    age: 40,
    phone: '65-9890-1231',
    address: '39 Marina Blvd, Singapore',
    gender: 'Male',
    complaint: 'Ankle sprain (severe)',
    vitals: { bp: '130/80', temp: '37.0°C', hr: '85 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Twisted ankle playing football. Significant swelling and pain.',
    sentiment: 'restless',
    priority: 'P2',
    NOK: 'Wife',
    status: Status.awaiting_tests,
    prevStatus: Status.doctor_consult,
    nextStatus: Status.test_in_progress,
    waitTime: 25,
    room: 'N/A',
    progress: 6,
    nextAction: 'X-ray of ankle',
    timeInStage: 15,
    arrivalTime: '4:15 PM',
  },
  {
    id: 'P045',
    name: 'Chloe Lim',
    age: 9,
    phone: '65-9012-3452',
    address: '40 Newton Rd, Singapore',
    gender: 'Female',
    complaint: 'Minor cough and cold',
    vitals: { bp: '95/60', temp: '37.3°C', hr: '88 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Symptoms started yesterday. No difficulty breathing.',
    sentiment: 'calm',
    priority: 'P4',
    NOK: 'Parents',
    status: Status.waiting_triage,
    prevStatus: Status.registration,
    nextStatus: Status.nurse_triage,
    waitTime: 10,
    room: 'N/A',
    progress: 2,
    nextAction: 'Nurse assessment',
    timeInStage: 5,
    arrivalTime: '5:00 PM',
  },
  {
    id: 'P046',
    name: 'Desmond Tan',
    age: 68,
    phone: '65-9123-4563',
    address: '41 Old Airport Rd, Singapore',
    gender: 'Male',
    complaint: 'Dizziness and blurred vision',
    vitals: { bp: '105/65', temp: '36.8°C', hr: '60 bpm', spo2: '97%' },
    allergies: [],
    medications: ['Beta-blockers'],
    medicalHistory: ['Arrhythmia'],
    notes: 'Symptoms intermittent. Not losing consciousness.',
    sentiment: 'tired',
    priority: 'P2',
    NOK: 'Wife',
    status: Status.bed_assigned,
    prevStatus: Status.awaiting_bed,
    nextStatus: Status.doctor_consult,
    waitTime: 10,
    room: 'Bed 8',
    progress: 4,
    nextAction: 'Doctor assessment, ECG',
    timeInStage: 5,
    arrivalTime: '5:15 PM',
  },
  {
    id: 'P047',
    name: 'Evelyn Foo',
    age: 55,
    phone: '65-9234-5674',
    address: '42 Potong Pasir Ave 1, Singapore',
    gender: 'Female',
    complaint: 'Persistent sore throat (chronic)',
    vitals: { bp: '120/75', temp: '37.1°C', hr: '72 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: ['Chronic Pharyngitis'],
    notes: 'Sore throat for 3 weeks. No fever.',
    sentiment: 'calm',
    priority: 'P3',
    NOK: 'Self',
    status: Status.waiting_room,
    prevStatus: Status.nurse_triage,
    nextStatus: Status.doctor_consult,
    waitTime: 40,
    room: 'N/A',
    progress: 3,
    nextAction: 'Doctor consultation',
    timeInStage: 25,
    arrivalTime: '4:40 PM',
  },
  {
    id: 'P048',
    name: 'Frederick Goh',
    age: 30,
    phone: '65-9345-6785',
    address: '43 Queensway, Singapore',
    gender: 'Male',
    complaint: 'Follow-up for stitches removal',
    vitals: { bp: '115/70', temp: '36.8°C', hr: '68 bpm', spo2: '99%' },
    allergies: [],
    medications: [],
    medicalHistory: ['Laceration (2 weeks ago)'],
    notes: 'Stitches on arm. Looks well healed.',
    sentiment: 'good',
    priority: 'P4',
    NOK: 'Self',
    status: Status.doctor_consult,
    prevStatus: Status.nurse_triage,
    nextStatus: Status.discharge_procedures,
    waitTime: 5,
    room: 'Treatment Room 2',
    progress: 5,
    nextAction: 'Stitches removal',
    timeInStage: 2,
    arrivalTime: '5:30 PM',
  },
  {
    id: 'P049',
    name: 'Gillian Ho',
    age: 23,
    phone: '65-9456-7896',
    address: '44 Rochester Park, Singapore',
    gender: 'Female',
    complaint: 'Sudden high fever and body aches',
    vitals: { bp: '110/70', temp: '39.2°C', hr: '95 bpm', spo2: '97%' },
    allergies: [],
    medications: [],
    medicalHistory: [],
    notes: 'Symptoms started abruptly today. Headache.',
    sentiment: 'tired',
    priority: 'P2',
    NOK: 'Partner',
    status: Status.nurse_triage,
    prevStatus: Status.arrived,
    nextStatus: Status.doctor_consult,
    waitTime: 12,
    room: 'N/A',
    progress: 2,
    nextAction: 'Nurse assessment, potential flu test',
    timeInStage: 8,
    arrivalTime: '5:45 PM',
  },
  {
    id: 'P050',
    name: 'Henry Lim',
    age: 66,
    phone: '65-9567-8907',
    address: '45 Sentosa Cove, Singapore',
    gender: 'Male',
    complaint: 'Shortness of breath on exertion',
    vitals: { bp: '150/92', temp: '36.9°C', hr: '88 bpm', spo2: '93%' },
    allergies: [],
    medications: ['Aspirin'],
    medicalHistory: ['Heart Disease', 'COPD'],
    notes: 'Worsening dyspnea over a week. Swollen ankles.',
    sentiment: 'restless',
    priority: 'P1',
    NOK: 'Wife',
    status: Status.bed_assigned,
    prevStatus: Status.awaiting_bed,
    nextStatus: Status.doctor_consult,
    waitTime: 7,
    room: 'Emergency Bay 5',
    progress: 4,
    nextAction: 'Immediate doctor assessment, oxygen, bloods',
    timeInStage: 4,
    arrivalTime: '6:00 PM',
  },
];

export const registeredPatients: RegisteredPatient[] = [
  {
    name: 'Alice Brown',
    age: 50,
    phone: '65-9789-0123',
    address: '12 Bukit Timah Rd, Singapore',
    gender: 'Female',
    NOK: 'John Brown (Husband) - 65-5432-1098',
  },
  {
    name: 'Benjamin Tan',
    age: 42,
    phone: '65-9123-1111',
    address: '88 Holland Ave, Singapore',
    gender: 'Male',
    NOK: 'Rachel Tan (Wife) - 65-8765-2222',
  },
  {
    name: 'Catherine Lim',
    age: 67,
    phone: '65-9345-2222',
    address: '23 Ang Mo Kio St 61, Singapore',
    gender: 'Female',
    NOK: 'Samuel Lim (Son) - 65-9988-3333',
  },
  {
    name: 'Daniel Wong',
    age: 31,
    phone: '65-9456-3333',
    address: '5 Tanjong Katong Rd, Singapore',
    gender: 'Male',
    NOK: 'Grace Wong (Sister) - 65-8877-4444',
  },
  {
    name: 'Evelyn Chua',
    age: 25,
    phone: '65-9567-4444',
    address: '19 Bedok North Ave 4, Singapore',
    gender: 'Female',
    NOK: 'Self',
  },
  {
    name: 'Farhan Rahman',
    age: 54,
    phone: '65-9678-5555',
    address: '77 Pasir Ris Dr 3, Singapore',
    gender: 'Male',
    NOK: 'Aisha Rahman (Wife) - 65-7766-5555',
  },
  {
    name: 'Grace Lee',
    age: 38,
    phone: '65-9788-6666',
    address: '34 Bukit Batok St 21, Singapore',
    gender: 'Female',
    NOK: 'Henry Lee (Husband) - 65-6655-6666',
  },
];
